SuperShaheenChemist.Web/ViewModels/StockViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SuperShaheenChemist.Web.ViewModels
{
    public class StockViewModel
    {

    }
}

SuperShaheenChemist.Web/Controllers/ProductController.cs
using SuperShaheenChemist.Entities;
using SuperShaheenChemist.Services;
using SuperShaheenChemist.Web.Models;
using SuperShaheenChemist.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SuperShaheenChemist.Web.Controllers
{
    public class ProductController : Controller
    {
        // GET: Product
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult add_new_product()
        {
            DropDownViewModels model = new DropDownViewModels();
            model.categories= CategoriesService.Instance.GetAllCategories();
            model.distributors = DistributorService.Instance.GetAllDistributors();
            model.companies = CompanyService.Instance.GetAllCompanies();
            model.medicinesTypes = MedicineTypeService.Instance.GetAllMedicineTypes();
            return View(model);
        }
        [HttpPost]
        public void Create(Product model)
        {
            ProductsService.Instance.SaveProduct(model);
        }
        public ActionResult GetData(JqueryDatatableParam param)
        {
            var products = ProductsService.Instance.GetProducts(); //This method is returning the IEnumerable employee from database 

            //Searching
            if (!string.IsNullOrEmpty(param.sSearch))
            {
                products = products.Where(x => x.ProductName.ToLower().Contains(param.sSearch.ToLower())
                                              || x.GenericName.ToLower().Contains(param.sSearch.ToLower())
                                              || x.BatchNo.ToLower().Contains(param.sSearch.ToLower())
                                              || x.BarCode.ToLower().Contains(param.sSearch.ToLower())
                                              || x.Location.ToLower().Contains(param.sSearch.ToLower())
                                              || x.ExpiryDate.ToString("dd'/'MM'/'yyyy").ToLower().Contains(param.sSearch.ToLower())).ToList();
            }

            //Sorting
            var sortColumnIndex = Convert.ToInt32(HttpContext.Request.QueryString["iSortCol_0"]);
            var sortDirection = HttpContext.Request.QueryString["sSortDir_0"];
            if (sortColumnIndex == 3)
            {
                products = sortDirection == "asc" ? products.OrderBy(c => c.ProductName).ToList() : products.OrderByDescending(c => c.ProductName).ToList();
            }
            else if (sortColumnIndex == 4)
            {
                products = sortDirection == "asc" ? products.OrderBy(c => c.GenericName).ToList() : products.OrderByDescending(c => c.GenericName).ToList();
            }
            else if (sortColumnIndex == 5)
            {
                products = sortDirection == "asc" ? products.OrderBy(c => c.PackRetailCost).ToList() : products.OrderByDescending(c => c.PackRetailCost).ToList();
            }
            else
            {
                Func<Product, string> orderingFunction = e => sortColumnIndex == 0 ? e.ProductName : sortColumnIndex == 1 ? e.Location : e.Location;

                products = sortDirection == "asc" ? products.OrderBy(orderingFunction).ToList() : products.OrderByDescending(orderingFunction).ToList();
            }

            //Pagination
            var displayResult = products.Skip(param.iDisplayStart)
               .Take(param.iDisplayLength).ToList();
            var totalRecords = products.Count();


            //Sending data 
            return Json(new
            {
                param.sEcho,
                iTotalRecords = totalRecords,
                iTotalDisplayRecords = totalRecords,
                aaData = displayResult
            }, JsonRequestBehavior.AllowGet);

        }
        public ActionResult Edit(int ID)
        {
            EditViewModel model = new EditViewModel();
            model.product = ProductsService.Instance.GetProduct(ID);
            model.categories = CategoriesService.Instance.GetAllCategories();
            model.distributors = DistributorService.Instance.GetAllDistributors();
            model.companies = CompanyService.Instance.GetAllCompanies();
            model.medicinesTypes = MedicineTypeService.Instance.GetAllMedicineTypes();
            return View(model);
        }


        [HttpPost]
        public ActionResult Edit(Product product)
        {
            ProductsService.Instance.UpdateProduct(product);
            //return PartialView(model);
            return new JsonResult { Data = new { status = true } };
        }
        [HttpPost]
        public ActionResult Delete(int ID)
        {
            ProductsService.Instance.DeleteProduct(ID);
            return new JsonResult { Data = new { status = true } };
            
        }
        public ActionResult OutOfStock()
        {
            var products=ProductsService.Instance.OutOfStockProducts();
            ViewBag.data = products;
            return View();
        }

        public ActionResult Stock()
        {
            var products = ProductsService.Instance.getStock();
            ViewBag.data = products;
            return View();
        }
        public ActionResult SaveMedicineType(string type)
        {
            PurchaseService.Instance.AddMedicineType(type);
            return Json("", JsonRequestBehavior.AllowGet);
        }
        public ActionResult SaveCompany(string company)
        {
            PurchaseService.Instance.SaveCompany(company);
            return Json("", JsonRequestBehavior.AllowGet);
        }
        public ActionResult SaveDistributor(string distributor)
        {
            PurchaseService.Instance.SaveDistributor(distributor);
            return Json("", JsonRequestBehavior.AllowGet);
        }
        public ActionResult SaveCategory(string category)
        {
            PurchaseService.Instance.SaveCategory(category);
            return Json("", JsonRequestBehavior.AllowGet);
        }
        public ActionResult showCompanyDropDownList()
        {
           var data= CompanyService.Instance.GetAllCompanies();
           return Json(data,JsonRequestBehavior.AllowGet);
        }
        public ActionResult GetDistributor()
        {
            var data = DistributorService.Instance.GetAllDistributors();
            return Json(data, JsonRequestBehavior.AllowGet);
        }
        public ActionResult GetCategories()
        {
            var data = CategoriesService.Instance.GetAllCategories();
            return Json(data, JsonRequestBehavior.AllowGet);
        }
        public ActionResult GetMedicineTypes()
        {
            var data = MedicineTypeService.Instance.GetAllMedicineTypes();
            return Json(data, JsonRequestBehavior.AllowGet);
        }
    }
}

SuperShaheenChemist.Web/Controllers/StockController.cs
using SuperShaheenChemist.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SuperShaheenChemist.Web.Controllers
{
    public class StockController : Controller
    {
        // GET: Stock
        public ActionResult Index()
        {
            return View();

        }
        public ActionResult ExpiredStock()
        {
            var stock = StockService.Instance.GetExpiryStock();
            ViewBag.data = stock;
            return View();
        }
    }
}

SuperShaheenChemist.Web/Views/Product/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<script src="~/Client/dist/js/sweetalert.min.js"></script>
<link href="~/Content/Css/datatable.min.css" rel="stylesheet" type="text/css"/>
<link href="~/Content/Css/responsive.datatable.min.css" rel="stylesheet" type="text/css" />
<link href="~/Content/Css/button.datatable.css" rel="stylesheet" type="text/css"/>
<h2>Index</h2>
<div class="row">
    <div class="col-sm-12">
        <div class="container tblcontainer responsive">
            <table class="display responsive nowrap table" id="tblProduct" style="width:100%">
                <thead>
                    <tr>
                        <th scope="col">ProductName</th>
                        <th scope="col">GenericName</th>
                        <th scope="col">Batch No</th>
                        <th scope="col">Bar Code</th>
                        <th scope="col">Unit Retail Price</th>
                        <th scope="col">Retail Cost</th>
                        <th scope="col">Edit</th>
                        <th scope="col">Delete</th>
                    </tr>
                </thead>
            </table>
        </div>

    </div>
</div>
<script src="~/Content/Js/dataTables.min.js"></script>
<script src="~/Content/Js/dataTables.responsive.min.js"></script>
<script src="~/Content/Js/buttons.html5.js"></script>
<script src="~/Content/Js/pdfmake.min.js"></script>
<script src="~/Content/Js/vfs_fonts.js"></script>
<!-- Below file is showing print button if this version is not used button will hide-->
<script src="~/Content/Js/dataTables.buttons.js"></script>
<script src="~/Content/Js/colVis.min.js"></script>
<script src="~/Content/Js/jszip.min.js"></script>
<script src="~/Content/Js/buttons.print.min.js"></script>
<script>
    $(document).ready(function () {
        bindDatatable();
        $('.tblcontainer').on('click', 'a.deleteBtn', function () {
            var table = $('#tblProduct').DataTable();
            swal({
                title: "Confirm",
                text: "Are you sure you want to Delete Product?",
                icon: "warning",
                buttons: true,
                dangerMode: true,
            })
            .then((willDelete) => {
                 if (willDelete) {
                        $.ajax(
                        {
                                type: 'POST',
                                url:'@Url.Action("Delete","Product")', /*'/Product/Delete',*/
                                data: {
                                    ID: $(this).attr('data-id')
                                }
                            }).done(function (response) {
                            table.row($(this).parents('tr')).remove().draw();
                            swal("Product Deleted!", "Product Deleted Successfully!", "success");
                        }).fail(function (XMLHttpRequest, textStatus, errorThrown) {
                                alert("Fail");
                        });
                 }
             });
        });
    });

    function bindDatatable() {
        var table = $('#tblProduct')
            .DataTable({
                dom: 'Blfrtip',
                buttons: [
                    'colvis',
                    {
                        extend: 'excel',
                        exportOptions: {
                            columns: [0,1,2,3,4,5]
                        }
                    },
                    {
                        extend: 'pdf',
                        exportOptions: {
                            columns: [0, 1, 2, 3, 4, 5]
                        }
                    },
                    {
                        extend: 'print',
                        exportOptions: {
                            columns: [0, 1, 2, 3, 4, 5]
                        }
                    }

                ],
                "sAjaxSource": "/Product/GetData",
                "bServerSide": true,
                "bProcessing": true,
                "bSearchable": true,
                "order": [[1, 'asc']],
                "language": {
                    "emptyTable": "No record found.",
                    "processing":
                        '<i class="fa fa-spinner fa-spin fa-3x fa-fw" style="color:#2a2b2b;"></i><span class="sr-only">Loading...</span> '
                },
                "columns": [
                    {
                        "data": "ProductName",
                        "searchable": true,
                        responsivePriority: 1
                    },
                    {
                        "data": "GenericName",
                        "searchable": true
                    },
                    {
                        "data": "BatchNo",
                        "searchable": true
                    },
                    {
                        "data": "BarCode",
                        "searchable": true
                    }, {
                        "data": "UnitRetail",
                        "searchable": true
                    }, {
                        "data": "PackRetailCost",
                        "searchable": true,
                        responsivePriority: 1
                    },
                    {
                        "data": "Id",
                        "className": "red",
                        "render": function (data) {
                            //return '<a class="deleteBtn" href="/product/edit/' + data + '">Edit</a>';
                            return '<a href="/product/Edit?ID=' + data + '" class="pointer">Edit</a>';
                        }
                    },
                    {
                        "data": "Id",
                        "className": "red",
                        "render": function (data) {
                            return '<a class="deleteBtn pointer" data-id=' + data + '>Delete</a>';
                        }
                    }
                ]
            });
    }
</script>

SuperShaheenChemist.Web/Views/Product/OutOfStock.cshtml
@{
    ViewBag.Title = "OutOfStock";
}
<link href="~/Content/Css/datatable.min.css" rel="stylesheet" type="text/css" />
<link href="~/Content/Css/responsive.datatable.min.css" rel="stylesheet" type="text/css" />
<link href="~/Content/Css/button.datatable.css" rel="stylesheet" type="text/css" />
<h2>Out Of Stock Products</h2>
<style>
    table.dataTable.display tbody tr > .sorting_1, table.dataTable.order-column.stripe tbody tr > .sorting_1 {
        background-color: #0000 !important;
    }
</style>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="table-responsive">
                <table class="table display responsive nowrap" id="purchaseItems">
                    <thead>
                        <tr>
                            <th>Product Name</th>
                            <th>Generic Name</th>
                            <th>Stock</th>
                            <th>Price</th>
                            <th>Total Amount</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in ViewBag.data)
                        {
                            <tr style="background-color: red !important;color:white !important;">
                                <td>@item.Product.ProductName</td>
                                <td>@item.Product.GenericName</td>
                                <td>@item.Stock</td>
                                <td>@item.Price</td>
                                <td>@item.TotalAmount</td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<script src="~/Content/Js/dataTables.min.js"></script>
<script src="~/Content/Js/dataTables.responsive.min.js"></script>
<script src="~/Content/Js/buttons.html5.js"></script>
<script src="~/Content/Js/pdfmake.min.js"></script>
<script src="~/Content/Js/vfs_fonts.js"></script>
<!-- Below file is showing print button if this version is not used button will hide-->
<script src="~/Content/Js/dataTables.buttons.js"></script>
<script src="~/Content/Js/colVis.min.js"></script>
<script src="~/Content/Js/jszip.min.js"></script>
<script src="~/Content/Js/buttons.print.min.js"></script>
<script>
    $(document).ready(function () {

        $('#purchaseItems').DataTable(
            {
                dom: 'Blfrtip',
                buttons: [
                    'colvis',
                    {
                        extend: 'excel',
                        exportOptions: {
                            columns: [0, 1, 2, 3, 4]
                        }
                    },
                    {
                        extend: 'pdf',
                        exportOptions: {
                            columns: [0, 1, 2, 3, 4]
                        }
                    },
                    {
                        extend: 'print',
                        exportOptions: {
                            columns: [0, 1, 2, 3, 4]
                        }
                    }

                ]
            }
        );

    });
</script>

SuperShaheenChemist.Web/Views/Product/Stock.cshtml
@{
    ViewBag.Title = "OutOfStock";
}
<link href="~/Content/Css/datatable.min.css" rel="stylesheet" type="text/css" />
<link href="~/Content/Css/responsive.datatable.min.css" rel="stylesheet" type="text/css" />
<link href="~/Content/Css/button.datatable.css" rel="stylesheet" type="text/css" />
<h2>Total Stock</h2>
<div class="container">

    <div class="row">
        <div class="col-md-12">
            <div class="table-responsive">
                <table class="table display responsive nowrap" id="purchaseItems">
                    <thead>
                        <tr>
                            <th>Product Name</th>
                            <th>Generic Name</th>
                            <th>Stock</th>
                            <th>Price</th>
                            <th>Total Amount</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in ViewBag.data)
                        {
                            <tr>
                                <td>@item.Product.ProductName</td>
                                <td>@item.Product.GenericName</td>
                                <td>@item.Stock</td>
                                <td>@item.Price</td>
                                <td>@item.TotalAmount</td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<script src="~/Content/Js/dataTables.min.js"></script>
<script src="~/Content/Js/dataTables.responsive.min.js"></script>
<script src="~/Content/Js/buttons.html5.js"></script>
<script src="~/Content/Js/pdfmake.min.js"></script>
<script src="~/Content/Js/vfs_fonts.js"></script>
<!-- Below file is showing print button if this version is not used button will hide-->
<script src="~/Content/Js/dataTables.buttons.js"></script>
<script src="~/Content/Js/colVis.min.js"></script>
<script src="~/Content/Js/jszip.min.js"></script>
<script src="~/Content/Js/buttons.print.min.js"></script>
<script>
    $(document).ready(function () {

        $('#purchaseItems').DataTable(
            {
                dom: 'Blfrtip',
                buttons: [
                    'colvis',
                    {
                        extend: 'excel',
                        exportOptions: {
                            columns: [0, 1, 2, 3, 4]
                        }
                    },
                    {
                        extend: 'pdf',
                        exportOptions: {
                            columns: [0, 1, 2, 3, 4]
                        }
                    },
                    {
                        extend: 'print',
                        exportOptions: {
                            columns: [0, 1, 2, 3, 4]
                        }
                    }

                ]
            }
        );

    });
</script>